#!/bin/sh
# Update the local .gitignore from a repository of predefined ignore lists.
# The repository is a clone of git://github.com/github/gitignore and
# the $GITIGNORE_REPO environment variable points to its directory.

if [ -z "$GITIGNORE_REPO" ] ; then
    echo '$GITIGNORE_REPO not set'
    exit
fi

if [ ! -d "$GITIGNORE_REPO" ] ; then
    echo '$GITIGNORE_REPO is no directory'
    exit
fi

if [ -z "$1" ] ; then
    echo "description: Update the local .gitignore from a repository of predefined ignore lists."
    echo "usage: $0 language"
    echo "usage: $0 'list'"
    echo "example: $0 Ruby"
    echo "example: $0 Global/Eclipse"
    echo "example: $0 list"
    exit
fi

if [ "$1" = "list" ] ; then
    files="`find "$GITIGNORE_REPO" -name '*.gitignore'`"
    for file in $files; do
       without_ext=${file%.*}
       echo ${without_ext#"$GITIGNORE_REPO/"}
    done
    exit
fi

infile="$GITIGNORE_REPO/$1.gitignore" 

if [ ! -f "$infile" ] ; then
    echo "No .gitignore found for $1"
    exit
fi

outfile='./.gitignore'

echo "# $1\n" >> "$outfile"
cat "$infile" >> "$outfile"
echo "\n"     >> "$outfile"
