#!/bin/sh

if [ -z "$GITIGNORE_REPO" ] ; then
    echo '$GITIGNORE_REPO not set'
    exit
fi

if [ ! -d "$GITIGNORE_REPO" ] ; then
    echo '$GITIGNORE_REPO is no directory'
    exit
fi

if [ -z "$1" ] ; then
    echo "usage: $0 language"
    echo "example: $0 Ruby"
    echo "example: $0 Global/Eclipse"
    exit
fi

if [ "$1" = "list" ] ; then
    files="$GITIGNORE_REPO/*.gitignore"; 
    for file in $files; do
       echo $(basename ${file%.*})
    done
    exit
fi

infile="$GITIGNORE_REPO/$1.gitignore" 

if [ ! -f "$infile" ] ; then
    echo "No .gitignore found for $1"
    exit
fi

outfile='./.gitignore'

echo "# $1\n" >> "$outfile"
cat "$infile" >> "$outfile"
echo "\n"     >> "$outfile"
